language: ruby
rvm:
  - 2.0.0
  - 2.1.1
  - 2.2.2
  - 2.3.0
  - 2.4.1
  - 2.5.7
  - 2.6.5
script: bundle exec rake
before_install:
  - gem update bundler
  - bundle --version
install: bundle install --jobs=3 --retry=3 --without deprecated
dist: trusty
sudo: false
